name: SoftSkills
description: Aplicativo móvel para formação e partilha de conhecimento interno.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Navegação
  go_router: ^12.1.3
  
  # FIREBASE COMENTADO TEMPORARIAMENTE:
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.10

  # Notificações locais
  flutter_local_notifications: ^17.0.0

  # Validação
  email_validator: ^2.1.17
  
  # UI e fontes
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # HTTP e comunicação
  http: ^1.1.0
  http_parser: ^4.0.2        # MediaType
  socket_io_client: ^2.0.3+1
  
  # Estado e armazenamento
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # Conectividade
  connectivity_plus: ^5.0.2
  
  # Ficheiros e media
  file_picker: ^8.1.6
  image_picker: ^1.1.2
  path: ^1.8.3              # Manipulação de caminhos
  mime: ^1.0.4              # Detecção de MIME types
  
  # Utils
  intl: ^0.18.1
  url_launcher: ^6.2.1

  # DEPENDÊNCIAS PARA O FÓRUM COM ANEXOS
  video_player: ^2.8.2          # Reprodução de vídeos nos anexos
  photo_view: ^0.14.0           # Visualização de imagens em tela cheia

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Adicionar assets se necessário
  # assets:
  #   - assets/images/
  #   - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48