name: SoftSkills
description: Aplicativo móvel para formação e partilha de conhecimento interno.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI e fontes
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # HTTP e comunicação
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  
  # Estado e armazenamento
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # Ficheiros e media
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  
  # Utils
  intl: ^0.18.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # ✅ REMOVIDO - Assets que causam problemas
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # ✅ REMOVIDO - Fontes que não existem
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #   - family: Arial
  #     fonts:
  #       - asset: assets/fonts/Arial-Regular.ttf
  #       - asset: assets/fonts/Arial-Bold.ttf
  #         weight: 700