name: projeto_mobile
description: Aplicativo móvel para formação e partilha de conhecimento interno.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.5
  http: ^1.3.0
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  intl: ^0.18.0
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  #fonts:
   # - family: Arial
    #  fonts:
     #   - asset: assets/fonts/Arial-Regular.ttf
      #  - asset: assets/fonts/Arial-Bold.ttf
       #   weight: 700